name: CI

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup JDK
              uses: actions/setup-java@v2.3.1
              with:
                  java-version: 11
                  distribution: adopt
                  java-package: jdk
            - name: Cache Gradle packages
              uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                  restore-keys: ${{ runner.os }}-gradle
            - name: Build
              run: |
                  chmod +x gradlew
                  ./gradlew build
            - name: Upload jar
              uses: actions/upload-artifact@v2
              with:
                  name: test-coverage
                  path: build/libs/Notifier.jar
